name: Test

on:
  push:
    branches:
  workflow_dispatch:
  

#  Only one of these jobs runs at a time per branch, this cancels the other running jobs
concurrency:
  group: ${{ github.ref }}
  # group: "main"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: | 
          echo "test in progress"
          echo "my testinfra xml" >> testinfra.xml
  
      - name: Upload testinfra results
        id: upload-testinfra-results
        uses: actions/upload-artifact@v4
        with:
          name: test_testinfra
          path: testinfra.xml
